export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const BUYING_PRODUCT = "BUYING_PRODUCT";
export const DECREASE_QY = "DECREASE_QY";
export const QUANTITY_CHANGE = "QUANTITY_CHANGE";
